url: "https://agnestyas.github.io"
baseurl: ""

# Site settings
title: Agnesningtyas
email: agnestyas.h@gmail.com
description: "Data Analyst Portfolio Project. Turn data into valueable insight and data driven decision."


# Team names, titles and social links
people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

- name: Agnesningtyas
  pic: 2
  position: Data Analyst
  social:
    - title: linkedin
      url: https://linkedin.com/in/agnesningtyas-hanindya
    - title: github
      url: https://github.com/agnestyas
    - title: medium
      url: https://agnestyas-h.medium.com

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty